language: node_js
node_js:
  - 0.12
  - 0.1
  - iojs
before_install:
  - npm i -g npm@latest
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
env:
  secure: wWT9FB/Hz5DdyNTSuIbuV6Hqbm1RzJky8xs/UsLinqw4z8TnxaNAtwlcXqHUJ0CVu7TfQXUhlnVrgxYQ7GNI6lCQZ7/OXFCPUaP6NyuJUfdXSzDv9Ho279KO91pLfQ0oclX/tAXvAAAk9MWUtSe9kInEyOE38YogrJNvzwczTi72we9KCMYOer6iDzUC1+BIFSdZiNujta4lz++aOFIdwRcnodtrFl+6Ut6prtmil++A4dPjrnpoaytCVOCwrmxG0USfSQJvmD73R0Du7X0ggUhI2S72z3/NxIkfzbp38QVbjkPwqVWwOZIVftaTcXlvQQyqdhdfDDYDwHTPi/7fajwJXGmGNJ1iq1vahfMdvxxtdXsJsN0WD60vMopcIrLRPMq8C2a2MQtKgHV2GeRu8dVofdHY2q0E+McVBVpru5S3SF+/YWWv4vpO9c9lei32rtXuvx+IHYllBn2T1J505ed+Ay4SXpDfYr0l4u+g8Bi/5+d4Ca6lH1h7oVlPaZumiJEL3w/f49LlUAzfwpPWkq5rTlOivksdauXKVigKTw9o1QfoeKR/DqCd/3HE/Q5JeQLvfEdGBt5hcmbkNWhdHP7HpG3W6s7mtkK2jrd91t4kET6xTKBjzxbqY1b9mc9WD/CCkhXP2gaIuagMA/Eq+LUd1GofQAGfnWQG9ipuGc8=
